
# uncomment once https://github.com/golang/dep/issues/899 is resolved
# required = ["k8s.io/code-generator"]
# [[constraint]]
#   name = "k8s.io/code-generator"
#   version = "kubernetes-1.10.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[prune]
  go-tests = true
