apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.atlasdb.infoblox.com
spec:
  group: atlasdb.infoblox.com
  version: v1alpha1
  names:
    kind: Database
    plural: databases
  scope: Namespaced
