/*
Copyright 2018 Infoblox, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/infobloxopen/atlas-db/pkg/apis/db/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDatabaseSchemas implements DatabaseSchemaInterface
type FakeDatabaseSchemas struct {
	Fake *FakeAtlasdbV1alpha1
	ns   string
}

var databaseschemasResource = schema.GroupVersionResource{Group: "atlasdb.infoblox.com", Version: "v1alpha1", Resource: "databaseschemas"}

var databaseschemasKind = schema.GroupVersionKind{Group: "atlasdb.infoblox.com", Version: "v1alpha1", Kind: "DatabaseSchema"}

// Get takes name of the databaseSchema, and returns the corresponding databaseSchema object, and an error if there is any.
func (c *FakeDatabaseSchemas) Get(name string, options v1.GetOptions) (result *v1alpha1.DatabaseSchema, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(databaseschemasResource, c.ns, name), &v1alpha1.DatabaseSchema{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseSchema), err
}

// List takes label and field selectors, and returns the list of DatabaseSchemas that match those selectors.
func (c *FakeDatabaseSchemas) List(opts v1.ListOptions) (result *v1alpha1.DatabaseSchemaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(databaseschemasResource, databaseschemasKind, c.ns, opts), &v1alpha1.DatabaseSchemaList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DatabaseSchemaList{}
	for _, item := range obj.(*v1alpha1.DatabaseSchemaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested databaseSchemas.
func (c *FakeDatabaseSchemas) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(databaseschemasResource, c.ns, opts))

}

// Create takes the representation of a databaseSchema and creates it.  Returns the server's representation of the databaseSchema, and an error, if there is any.
func (c *FakeDatabaseSchemas) Create(databaseSchema *v1alpha1.DatabaseSchema) (result *v1alpha1.DatabaseSchema, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(databaseschemasResource, c.ns, databaseSchema), &v1alpha1.DatabaseSchema{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseSchema), err
}

// Update takes the representation of a databaseSchema and updates it. Returns the server's representation of the databaseSchema, and an error, if there is any.
func (c *FakeDatabaseSchemas) Update(databaseSchema *v1alpha1.DatabaseSchema) (result *v1alpha1.DatabaseSchema, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(databaseschemasResource, c.ns, databaseSchema), &v1alpha1.DatabaseSchema{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseSchema), err
}

// Delete takes name of the databaseSchema and deletes it. Returns an error if one occurs.
func (c *FakeDatabaseSchemas) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(databaseschemasResource, c.ns, name), &v1alpha1.DatabaseSchema{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDatabaseSchemas) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(databaseschemasResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DatabaseSchemaList{})
	return err
}

// Patch applies the patch and returns the patched databaseSchema.
func (c *FakeDatabaseSchemas) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DatabaseSchema, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(databaseschemasResource, c.ns, name, data, subresources...), &v1alpha1.DatabaseSchema{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseSchema), err
}
