/*
Copyright 2018 Infoblox, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/infobloxopen/atlas/pkg/apis/atlasauthz/v1alpha1"
	scheme "github.com/infobloxopen/atlas/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AppRolesGetter has a method to return a AppRoleInterface.
// A group's client should implement this interface.
type AppRolesGetter interface {
	AppRoles(namespace string) AppRoleInterface
}

// AppRoleInterface has methods to work with AppRole resources.
type AppRoleInterface interface {
	Create(*v1alpha1.AppRole) (*v1alpha1.AppRole, error)
	Update(*v1alpha1.AppRole) (*v1alpha1.AppRole, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AppRole, error)
	List(opts v1.ListOptions) (*v1alpha1.AppRoleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AppRole, err error)
	AppRoleExpansion
}

// appRoles implements AppRoleInterface
type appRoles struct {
	client rest.Interface
	ns     string
}

// newAppRoles returns a AppRoles
func newAppRoles(c *AtlasauthzV1alpha1Client, namespace string) *appRoles {
	return &appRoles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the appRole, and returns the corresponding appRole object, and an error if there is any.
func (c *appRoles) Get(name string, options v1.GetOptions) (result *v1alpha1.AppRole, err error) {
	result = &v1alpha1.AppRole{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("approles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AppRoles that match those selectors.
func (c *appRoles) List(opts v1.ListOptions) (result *v1alpha1.AppRoleList, err error) {
	result = &v1alpha1.AppRoleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("approles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested appRoles.
func (c *appRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("approles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a appRole and creates it.  Returns the server's representation of the appRole, and an error, if there is any.
func (c *appRoles) Create(appRole *v1alpha1.AppRole) (result *v1alpha1.AppRole, err error) {
	result = &v1alpha1.AppRole{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("approles").
		Body(appRole).
		Do().
		Into(result)
	return
}

// Update takes the representation of a appRole and updates it. Returns the server's representation of the appRole, and an error, if there is any.
func (c *appRoles) Update(appRole *v1alpha1.AppRole) (result *v1alpha1.AppRole, err error) {
	result = &v1alpha1.AppRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("approles").
		Name(appRole.Name).
		Body(appRole).
		Do().
		Into(result)
	return
}

// Delete takes name of the appRole and deletes it. Returns an error if one occurs.
func (c *appRoles) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("approles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *appRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("approles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched appRole.
func (c *appRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AppRole, err error) {
	result = &v1alpha1.AppRole{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("approles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
