/*
Copyright 2018 Infoblox, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	db_v1alpha1 "github.com/infobloxopen/atlas-db/pkg/apis/db/v1alpha1"
	versioned "github.com/infobloxopen/atlas-db/pkg/client/clientset/versioned"
	internalinterfaces "github.com/infobloxopen/atlas-db/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/infobloxopen/atlas-db/pkg/client/listers/db/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DatabaseSchemaInformer provides access to a shared informer and lister for
// DatabaseSchemas.
type DatabaseSchemaInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DatabaseSchemaLister
}

type databaseSchemaInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDatabaseSchemaInformer constructs a new informer for DatabaseSchema type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDatabaseSchemaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDatabaseSchemaInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDatabaseSchemaInformer constructs a new informer for DatabaseSchema type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDatabaseSchemaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AtlasdbV1alpha1().DatabaseSchemas(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AtlasdbV1alpha1().DatabaseSchemas(namespace).Watch(options)
			},
		},
		&db_v1alpha1.DatabaseSchema{},
		resyncPeriod,
		indexers,
	)
}

func (f *databaseSchemaInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDatabaseSchemaInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *databaseSchemaInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&db_v1alpha1.DatabaseSchema{}, f.defaultInformer)
}

func (f *databaseSchemaInformer) Lister() v1alpha1.DatabaseSchemaLister {
	return v1alpha1.NewDatabaseSchemaLister(f.Informer().GetIndexer())
}
