apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databaseservers.atlasdb.infoblox.com
spec:
  group: atlasdb.infoblox.com
  version: v1alpha1
  names:
    kind: DatabaseServer
    plural: databaseservers
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.atlasdb.infoblox.com
spec:
  group: atlasdb.infoblox.com
  version: v1alpha1
  names:
    kind: Database
    plural: databases
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databaseschemas.atlasdb.infoblox.com
spec:
  group: atlasdb.infoblox.com
  version: v1alpha1
  names:
    kind: DatabaseSchema
    plural: databaseschemas
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - database
            - git
            - version
          properties:
            database:
              type: string
            git:
              type: string
            version:
              type: integer
              minimum: 0
