apiVersion: atlasdb.infoblox.com/v1alpha1
kind: Database
metadata:
  name: mydb
spec:
  server: mydbserver
  users:
  - name: admin
    password: admin
    role: admin
  - name: you
    password: bar
    role: read
