apiVersion: atlasdb.infoblox.com/v1alpha1
kind: DatabaseServer
metadata:
  name: mydbserver
spec:
  servicePort: 3306
  superUser: "postgres"
  superUserPassword: "root"
  mySQL:
    image: mysql
---
apiVersion: atlasdb.infoblox.com/v1alpha1
kind: Database
metadata:
  name: mydb
spec:
  users:
  - name: me
    password: foo
    role: admin
  - name: you
    password: bar
    role: read
  server: mydbserver
---
apiVersion: atlasdb.infoblox.com/v1alpha1
kind: DatabaseSchema
metadata:
  name: myschema
spec:
  database: mydb
  git: github://<GITHUB USERNAME>:<GITHUB PASSWORD>@infobloxopen/atlas-contacts-app/db/migrations
  version: 001
