apiVersion: atlasdb.infoblox.com/v1alpha1
kind: DatabaseServer
metadata:
  name: mydbserver
spec:
  servicePort: 5432
  superUserFrom:
    secretKeyRef:
      name: mydbsecrets
      key: superUser
  superUserPasswordFrom:
    secretKeyRef:
      name: mydbsecrets
      key: superUserPassword
  postgres:
    image: postgres
---
apiVersion: atlasdb.infoblox.com/v1alpha1
kind: Database
metadata:
  name: myappdb
spec:
  users:
  - name: me
    passwordFrom:
      secretKeyRef:
        name: mydbsecrets
        key: adminUserPass
    role: admin
  - name: you
    passwordFrom:
      secretKeyRef:
        name: mydbsecrets
        key: readUserPass
    role: read
  serverType: postgres
  server: mydbserver
---
apiVersion: atlasdb.infoblox.com/v1alpha1
kind: DatabaseSchema
metadata:
  name: myappschema
spec:
  database: myappdb
  gitFrom:
    secretKeyRef:
      name: mydbsecrets
      key: gitURL
  version: 001
