apiVersion: atlasdb.infoblox.com/v1alpha1
kind: DatabaseServer
metadata:
  name: mydbserver
spec:
  servicePort: 5432
  superUser: "postgres"
  superUserPassword: "postgres"
  postgres:
    image: postgres
---
apiVersion: atlasdb.infoblox.com/v1alpha1
kind: Database
metadata:
  name: myappdb
spec:
  users:
  - name: me
    password: foo
    role: admin
  - name: you
    password: bar
    role: read
  serverType: postgres
  server: mydbserver
---
apiVersion: atlasdb.infoblox.com/v1alpha1
kind: DatabaseSchema
metadata:
  name: myappschema
spec:
  database: myappdb
  git: github://iburak-infoblox:<place password or oauth token here>@iburak-infoblox/atlas-contacts-app/db/migrations
  version: 100
