apiVersion: atlasdb.infoblox.com/v1alpha1
kind: DatabaseSchema
metadata:
  name: myschema
spec:
  abyrvalg: primus
  database: mydb
  git: github://iburak-infoblox:<place password or oauth token here>@iburak-infoblox/atlas-contacts-app/migrations
  version: 100

