/*
Copyright 2018 Infoblox, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "github.com/infobloxopen/atlas/pkg/client/clientset/versioned"
	atlasauthzv1alpha1 "github.com/infobloxopen/atlas/pkg/client/clientset/versioned/typed/atlasauthz/v1alpha1"
	fakeatlasauthzv1alpha1 "github.com/infobloxopen/atlas/pkg/client/clientset/versioned/typed/atlasauthz/v1alpha1/fake"
	atlasdbv1alpha1 "github.com/infobloxopen/atlas/pkg/client/clientset/versioned/typed/atlasdb/v1alpha1"
	fakeatlasdbv1alpha1 "github.com/infobloxopen/atlas/pkg/client/clientset/versioned/typed/atlasdb/v1alpha1/fake"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	fakePtr := testing.Fake{}
	fakePtr.AddReactor("*", "*", testing.ObjectReaction(o))
	fakePtr.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return &Clientset{fakePtr, &fakediscovery.FakeDiscovery{Fake: &fakePtr}}
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

var _ clientset.Interface = &Clientset{}

// AtlasauthzV1alpha1 retrieves the AtlasauthzV1alpha1Client
func (c *Clientset) AtlasauthzV1alpha1() atlasauthzv1alpha1.AtlasauthzV1alpha1Interface {
	return &fakeatlasauthzv1alpha1.FakeAtlasauthzV1alpha1{Fake: &c.Fake}
}

// Atlasauthz retrieves the AtlasauthzV1alpha1Client
func (c *Clientset) Atlasauthz() atlasauthzv1alpha1.AtlasauthzV1alpha1Interface {
	return &fakeatlasauthzv1alpha1.FakeAtlasauthzV1alpha1{Fake: &c.Fake}
}

// AtlasdbV1alpha1 retrieves the AtlasdbV1alpha1Client
func (c *Clientset) AtlasdbV1alpha1() atlasdbv1alpha1.AtlasdbV1alpha1Interface {
	return &fakeatlasdbv1alpha1.FakeAtlasdbV1alpha1{Fake: &c.Fake}
}

// Atlasdb retrieves the AtlasdbV1alpha1Client
func (c *Clientset) Atlasdb() atlasdbv1alpha1.AtlasdbV1alpha1Interface {
	return &fakeatlasdbv1alpha1.FakeAtlasdbV1alpha1{Fake: &c.Fake}
}
