/*
Copyright 2018 Infoblox, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	atlas_v1alpha1 "github.com/infobloxopen/atlas/pkg/apis/atlas/v1alpha1"
	versioned "github.com/infobloxopen/atlas/pkg/client/clientset/versioned"
	internalinterfaces "github.com/infobloxopen/atlas/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/infobloxopen/atlas/pkg/client/listers/atlas/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DatabaseServerInformer provides access to a shared informer and lister for
// DatabaseServers.
type DatabaseServerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DatabaseServerLister
}

type databaseServerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDatabaseServerInformer constructs a new informer for DatabaseServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDatabaseServerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDatabaseServerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDatabaseServerInformer constructs a new informer for DatabaseServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDatabaseServerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AtlasV1alpha1().DatabaseServers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AtlasV1alpha1().DatabaseServers(namespace).Watch(options)
			},
		},
		&atlas_v1alpha1.DatabaseServer{},
		resyncPeriod,
		indexers,
	)
}

func (f *databaseServerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDatabaseServerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *databaseServerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&atlas_v1alpha1.DatabaseServer{}, f.defaultInformer)
}

func (f *databaseServerInformer) Lister() v1alpha1.DatabaseServerLister {
	return v1alpha1.NewDatabaseServerLister(f.Informer().GetIndexer())
}
