/*
Copyright 2018 Infoblox, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/infobloxopen/atlas-db/pkg/apis/db/v1alpha1"
	scheme "github.com/infobloxopen/atlas-db/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DatabaseServersGetter has a method to return a DatabaseServerInterface.
// A group's client should implement this interface.
type DatabaseServersGetter interface {
	DatabaseServers(namespace string) DatabaseServerInterface
}

// DatabaseServerInterface has methods to work with DatabaseServer resources.
type DatabaseServerInterface interface {
	Create(*v1alpha1.DatabaseServer) (*v1alpha1.DatabaseServer, error)
	Update(*v1alpha1.DatabaseServer) (*v1alpha1.DatabaseServer, error)
	UpdateStatus(*v1alpha1.DatabaseServer) (*v1alpha1.DatabaseServer, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DatabaseServer, error)
	List(opts v1.ListOptions) (*v1alpha1.DatabaseServerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DatabaseServer, err error)
	DatabaseServerExpansion
}

// databaseServers implements DatabaseServerInterface
type databaseServers struct {
	client rest.Interface
	ns     string
}

// newDatabaseServers returns a DatabaseServers
func newDatabaseServers(c *AtlasdbV1alpha1Client, namespace string) *databaseServers {
	return &databaseServers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the databaseServer, and returns the corresponding databaseServer object, and an error if there is any.
func (c *databaseServers) Get(name string, options v1.GetOptions) (result *v1alpha1.DatabaseServer, err error) {
	result = &v1alpha1.DatabaseServer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("databaseservers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DatabaseServers that match those selectors.
func (c *databaseServers) List(opts v1.ListOptions) (result *v1alpha1.DatabaseServerList, err error) {
	result = &v1alpha1.DatabaseServerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("databaseservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested databaseServers.
func (c *databaseServers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("databaseservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a databaseServer and creates it.  Returns the server's representation of the databaseServer, and an error, if there is any.
func (c *databaseServers) Create(databaseServer *v1alpha1.DatabaseServer) (result *v1alpha1.DatabaseServer, err error) {
	result = &v1alpha1.DatabaseServer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("databaseservers").
		Body(databaseServer).
		Do().
		Into(result)
	return
}

// Update takes the representation of a databaseServer and updates it. Returns the server's representation of the databaseServer, and an error, if there is any.
func (c *databaseServers) Update(databaseServer *v1alpha1.DatabaseServer) (result *v1alpha1.DatabaseServer, err error) {
	result = &v1alpha1.DatabaseServer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("databaseservers").
		Name(databaseServer.Name).
		Body(databaseServer).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
func (c *databaseServers) UpdateStatus(databaseServer *v1alpha1.DatabaseServer) (result *v1alpha1.DatabaseServer, err error) {
	result = &v1alpha1.DatabaseServer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("databaseservers").
		Name(databaseServer.Name).
		SubResource("status").
		Body(databaseServer).
		Do().
		Into(result)
	return
}

// Delete takes name of the databaseServer and deletes it. Returns an error if one occurs.
func (c *databaseServers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("databaseservers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *databaseServers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("databaseservers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched databaseServer.
func (c *databaseServers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DatabaseServer, err error) {
	result = &v1alpha1.DatabaseServer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("databaseservers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
