/*
Copyright 2018 Infoblox, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/infobloxopen/atlas-db/pkg/apis/db/v1alpha1"
	scheme "github.com/infobloxopen/atlas-db/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DatabaseSchemasGetter has a method to return a DatabaseSchemaInterface.
// A group's client should implement this interface.
type DatabaseSchemasGetter interface {
	DatabaseSchemas(namespace string) DatabaseSchemaInterface
}

// DatabaseSchemaInterface has methods to work with DatabaseSchema resources.
type DatabaseSchemaInterface interface {
	Create(*v1alpha1.DatabaseSchema) (*v1alpha1.DatabaseSchema, error)
	Update(*v1alpha1.DatabaseSchema) (*v1alpha1.DatabaseSchema, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DatabaseSchema, error)
	List(opts v1.ListOptions) (*v1alpha1.DatabaseSchemaList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DatabaseSchema, err error)
	DatabaseSchemaExpansion
}

// databaseSchemas implements DatabaseSchemaInterface
type databaseSchemas struct {
	client rest.Interface
	ns     string
}

// newDatabaseSchemas returns a DatabaseSchemas
func newDatabaseSchemas(c *AtlasdbV1alpha1Client, namespace string) *databaseSchemas {
	return &databaseSchemas{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the databaseSchema, and returns the corresponding databaseSchema object, and an error if there is any.
func (c *databaseSchemas) Get(name string, options v1.GetOptions) (result *v1alpha1.DatabaseSchema, err error) {
	result = &v1alpha1.DatabaseSchema{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("databaseschemas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DatabaseSchemas that match those selectors.
func (c *databaseSchemas) List(opts v1.ListOptions) (result *v1alpha1.DatabaseSchemaList, err error) {
	result = &v1alpha1.DatabaseSchemaList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("databaseschemas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested databaseSchemas.
func (c *databaseSchemas) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("databaseschemas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a databaseSchema and creates it.  Returns the server's representation of the databaseSchema, and an error, if there is any.
func (c *databaseSchemas) Create(databaseSchema *v1alpha1.DatabaseSchema) (result *v1alpha1.DatabaseSchema, err error) {
	result = &v1alpha1.DatabaseSchema{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("databaseschemas").
		Body(databaseSchema).
		Do().
		Into(result)
	return
}

// Update takes the representation of a databaseSchema and updates it. Returns the server's representation of the databaseSchema, and an error, if there is any.
func (c *databaseSchemas) Update(databaseSchema *v1alpha1.DatabaseSchema) (result *v1alpha1.DatabaseSchema, err error) {
	result = &v1alpha1.DatabaseSchema{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("databaseschemas").
		Name(databaseSchema.Name).
		Body(databaseSchema).
		Do().
		Into(result)
	return
}

// Delete takes name of the databaseSchema and deletes it. Returns an error if one occurs.
func (c *databaseSchemas) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("databaseschemas").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *databaseSchemas) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("databaseschemas").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched databaseSchema.
func (c *databaseSchemas) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DatabaseSchema, err error) {
	result = &v1alpha1.DatabaseSchema{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("databaseschemas").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
