/*
Copyright 2018 Infoblox, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	glog "github.com/golang/glog"
	atlasauthzv1alpha1 "github.com/infobloxopen/atlas/pkg/client/clientset/versioned/typed/atlasauthz/v1alpha1"
	atlasdbv1alpha1 "github.com/infobloxopen/atlas/pkg/client/clientset/versioned/typed/atlasdb/v1alpha1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	AtlasauthzV1alpha1() atlasauthzv1alpha1.AtlasauthzV1alpha1Interface
	// Deprecated: please explicitly pick a version if possible.
	Atlasauthz() atlasauthzv1alpha1.AtlasauthzV1alpha1Interface
	AtlasdbV1alpha1() atlasdbv1alpha1.AtlasdbV1alpha1Interface
	// Deprecated: please explicitly pick a version if possible.
	Atlasdb() atlasdbv1alpha1.AtlasdbV1alpha1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	atlasauthzV1alpha1 *atlasauthzv1alpha1.AtlasauthzV1alpha1Client
	atlasdbV1alpha1    *atlasdbv1alpha1.AtlasdbV1alpha1Client
}

// AtlasauthzV1alpha1 retrieves the AtlasauthzV1alpha1Client
func (c *Clientset) AtlasauthzV1alpha1() atlasauthzv1alpha1.AtlasauthzV1alpha1Interface {
	return c.atlasauthzV1alpha1
}

// Deprecated: Atlasauthz retrieves the default version of AtlasauthzClient.
// Please explicitly pick a version.
func (c *Clientset) Atlasauthz() atlasauthzv1alpha1.AtlasauthzV1alpha1Interface {
	return c.atlasauthzV1alpha1
}

// AtlasdbV1alpha1 retrieves the AtlasdbV1alpha1Client
func (c *Clientset) AtlasdbV1alpha1() atlasdbv1alpha1.AtlasdbV1alpha1Interface {
	return c.atlasdbV1alpha1
}

// Deprecated: Atlasdb retrieves the default version of AtlasdbClient.
// Please explicitly pick a version.
func (c *Clientset) Atlasdb() atlasdbv1alpha1.AtlasdbV1alpha1Interface {
	return c.atlasdbV1alpha1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.atlasauthzV1alpha1, err = atlasauthzv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.atlasdbV1alpha1, err = atlasdbv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		glog.Errorf("failed to create the DiscoveryClient: %v", err)
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.atlasauthzV1alpha1 = atlasauthzv1alpha1.NewForConfigOrDie(c)
	cs.atlasdbV1alpha1 = atlasdbv1alpha1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.atlasauthzV1alpha1 = atlasauthzv1alpha1.New(c)
	cs.atlasdbV1alpha1 = atlasdbv1alpha1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
